feat: new plugin for Scallop protocol
sonarwatch/portfolio pull request #2
Opened 2023-10-09 17:24 UTC by mr-donor

## Description
Add Scallop plugin.

Features:
- Jobs: MarketJob, PoolsJob, AddressJob
- Fetchers: LendingFetcher, ObligationFetcher

2023-10-16 14:11 UTC, GuillaumeCrmt commented
**Feedbacks on what you should modify :** 
- Each Obligation accounts should have a dedicated **PortfolioElement** as each account has dedicated risk ratio and liquidation threshold.
- The name of each Obligation account can be the shortened address of the account + " Obligations" , similar to how you display it on Scallop UI.
- Yields for lending seems to not match what you display on your UI (getting 0.007% supply APR for SUI coin where your UI is saying 22.02%)

**Some things I noticed that deserve to be raised :** 
- Do you think you could include "Pending Rewards" inside the lending fetcher ? We have a RewardAssets array dedicated to this.
- You don't split Lendings from sCoin Pools, is it intentional ? It could lose user on where is what.
- There is no supply Yield for obligations ?

Overall good work!

2023-10-25 03:42 UTC, nicetomeetyou1 commented
Updated Feature: 
- Add "Pending Rewards" inside the lending fetcher
- Each obligation has a dedicated **PortfolioElement**

Answers to your questions:


> Yields for lending seems to not match what you display on your UI (getting 0.007% supply APR for SUI coin where your UI is saying 22.02%)

For situations where APR does not match in UI, it is because the UI version APR is a sum of spool APR and lending APR. We do not combine the spool APR with lending APR in the lending fetcher because spool incentive will eventually end.`

> You don't split Lendings from sCoin Pools, is it intentional ? It could lose user on where is what.

Yes, it is intentional, we treat the lending pool and spool as a whole intentionally.

> There is no supply Yield for obligations ?

Yes, there is no supply Yield for depositing collateral.

2023-11-14 12:44 UTC, GuillaumeCrmt requested changes
Very small changes to make.

2023-11-14 12:44 UTC, GuillaumeCrmt commented on packages/plugins/src/plugins/scallop/obligationsFetcher.ts
> +    }
Should add zero length protection to avoid sending empty elements : 
`    if (
      suppliedAssets.length === 0 &&
      borrowedAssets.length === 0 &&
      rewardAssets.length === 0
    )
      continue;`

2023-11-14 12:44 UTC, GuillaumeCrmt commented on packages/plugins/src/plugins/scallop/lendingsFetcher.ts
> +
You can add a verification on the amount here to skip empty values
`if (assetValue.amount.isZero()) continue;`

2023-11-14 12:44 UTC, GuillaumeCrmt commented on packages/plugins/src/plugins/scallop/lendingsFetcher.ts
> +  }
Also add here a zero length check 
`
  if (
    suppliedAssets.length === 0 &&
    borrowedAssets.length === 0 &&
    rewardAssets.length === 0
  )
    return [];
`

2023-11-14 12:44 UTC, GuillaumeCrmt commented on packages/plugins/src/plugins/scallop/lendingsFetcher.ts
> +    name: 'Scallop Lending',
You can remove the name 'Scallop lending', it's a duplicate with the Label and platform name.

2023-11-14 12:44 UTC, GuillaumeCrmt commented on packages/plugins/src/plugins/scallop/constants.ts
> +    image: `https://alpha.sonar.watch/img/platforms/${platformId}.png`
You can remove the 'alpha' here. Our website is live for everyone now so it's sonar.watch

2024-03-14 20:47 UTC, GrayFieth approved these changes

2024-04-16 09:04 UTC, closed without merging

2024-05-26 01:35 UTC, GrayFieth commented
Merge